# YOUR NAME OR TITLE OF YOUR SITE
name: Vanessa Barcelos

# YOUR BRAND/PERSONAL TAGLINE
tagline: English PhD Researcher and Instructor at the University of Miami

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/vanessabcs.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://www.linkpicture.com/q/doors_medieval.jpeg

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # GITHUB
  - Name: DH Projects 2023
    URL: https://vanessabcs.github.io/DH2023/
    Username: 
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # GITHUB
  - Name: DH Projects 2022
    URL: https://vanessabcs.github.io/DH2022/
    Username: 
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: Vanessa25974839
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: teachervanessab
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram
    # Cal.com
    
   # GITHUB
  - Name: About me
    URL: https://vanessabcs.github.io/DH2023/aboutme
    Username: 
    Color: '#6e5494'
    Icon-Class: fab fa-github
 

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: ''

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /home

# Default Markdown Engine
markdown: kramdown
