# YOUR NAME OR TITLE OF YOUR SITE
name: Vanessa Barcelos

# YOUR BRAND/PERSONAL TAGLINE
tagline: English PhD Researcher and Instructor at the University of Miami

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/vanessabcs.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://www.linkpicture.com/q/doors_medieval.jpeg

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
      # GITHUB
  - Name: Github Directory
    URL: https://github.com/vanessabcs
    Username: 
    Color: '#923b20'
    Icon-Class: fab fa-github
    
     # About me Page
  - Name: About me
    URL: https://vanessabcs.github.io/DH2023/aboutme/
    Username: 
    Color: '#923b20'
    Icon-Class: 
   
    
        # Dreaming in Cuban
  - Name: Dreaming in Cuban
    URL: https://storymaps.arcgis.com/stories/f82a7f09276f4dbb96b5784bfd5e479d
    Username: 
    Color: '#923b20'
    Icon-Class: 
    
    # Newes from Scotland
  - Name: Newes from Scotland
    URL: https://vanessabcs.github.io/DH2023/aboutme/
    Username: 
    Color: '#923b20'
    Icon-Class: 
 
    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: Vanessa25974839
    Color: '#923b20'
    Icon-Class: fab fa-twitter
    

 

    
# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: ''

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /home

# Default Markdown Engine
markdown: kramdown
